[versions]
project = "2.2.20"

kotlin = "2.2.20"
dokka = "2.1.0"
buildconfig = "5.7.0"
exportPublic = "2.2.20"
vanniktech = "0.34.0"

[libraries]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
exportPublic =  { id = "net.akehurst.kotlin.gradle.plugin.exportPublic", version.ref = "exportPublic" }
buildconfig =  { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
vanniktech-maven-publish = { id="com.vanniktech.maven.publish", version.ref="vanniktech" }

